/**
 * WellNet API gate for mobile apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ResponseSignUpModelData;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseSignUpModel {
  
  @SerializedName("message")
  private String message = null;
  @SerializedName("success")
  private Boolean success = null;
  @SerializedName("errors")
  private List<String> errors = null;
  @SerializedName("data")
  private List<ResponseSignUpModelData> data = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getErrors() {
    return errors;
  }
  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ResponseSignUpModelData> getData() {
    return data;
  }
  public void setData(List<ResponseSignUpModelData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseSignUpModel responseSignUpModel = (ResponseSignUpModel) o;
    return (this.message == null ? responseSignUpModel.message == null : this.message.equals(responseSignUpModel.message)) &&
        (this.success == null ? responseSignUpModel.success == null : this.success.equals(responseSignUpModel.success)) &&
        (this.errors == null ? responseSignUpModel.errors == null : this.errors.equals(responseSignUpModel.errors)) &&
        (this.data == null ? responseSignUpModel.data == null : this.data.equals(responseSignUpModel.data));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.errors == null ? 0: this.errors.hashCode());
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseSignUpModel {\n");
    
    sb.append("  message: ").append(message).append("\n");
    sb.append("  success: ").append(success).append("\n");
    sb.append("  errors: ").append(errors).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
