/**
 * WellNet API gate for mobile apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReuaestLoginModel {
  
  @SerializedName("email")
  private String email = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("os")
  private String os = null;
  @SerializedName("push_token")
  private String pushToken = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOs() {
    return os;
  }
  public void setOs(String os) {
    this.os = os;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPushToken() {
    return pushToken;
  }
  public void setPushToken(String pushToken) {
    this.pushToken = pushToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReuaestLoginModel reuaestLoginModel = (ReuaestLoginModel) o;
    return (this.email == null ? reuaestLoginModel.email == null : this.email.equals(reuaestLoginModel.email)) &&
        (this.password == null ? reuaestLoginModel.password == null : this.password.equals(reuaestLoginModel.password)) &&
        (this.os == null ? reuaestLoginModel.os == null : this.os.equals(reuaestLoginModel.os)) &&
        (this.pushToken == null ? reuaestLoginModel.pushToken == null : this.pushToken.equals(reuaestLoginModel.pushToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.os == null ? 0: this.os.hashCode());
    result = 31 * result + (this.pushToken == null ? 0: this.pushToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReuaestLoginModel {\n");
    
    sb.append("  email: ").append(email).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  os: ").append(os).append("\n");
    sb.append("  pushToken: ").append(pushToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
